runtime: php

handlers:
  # Serve your app through a front controller at index.php or public/index.php.
  - url: .*
    script: auto

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "8.3"
  document_root: .

env_variables:
  INSTANCE_UNIX_SOCKET: /cloudsql/<PROJECT-ID>:<INSTANCE-REGION>:<INSTANCE-NAME>
  DB_USER: root
  DB_PASS:
  DB_NAME: root
