/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AddProductImport } from './routes/addProduct'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const AddProductRoute = AddProductImport.update({
  path: '/addProduct',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/addProduct': {
      id: '/addProduct'
      path: '/addProduct'
      fullPath: '/addProduct'
      preLoaderRoute: typeof AddProductImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({ IndexRoute, AddProductRoute })

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/addProduct"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/addProduct": {
      "filePath": "addProduct.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
